### ISSUE TITLE
Go source

### ISSUE THREAD

**Issue by drewwells** [andyshinn/alpine-pkg-go#1]
Thanks for setting this up! I noticed that after installing this package, the source is not provided in `$GOROOT`. /usr/lib/go/pkg directory is populated, but src is empty. This results in build errors when using anything from the standard library.

It looks like the standard lib source needs to be populated.

```
test.go:4:2: cannot find package "bufio" in any of:
	/usr/lib/go/src/bufio (from $GOROOT)
	($GOPATH not set)
test.go:5:2: cannot find package "fmt" in any of:
	/usr/lib/go/src/fmt (from $GOROOT)
	($GOPATH not set)
test.go:6:2: cannot find package "net" in any of:
	/usr/lib/go/src/net (from $GOROOT)
	($GOPATH not set)
test.go:7:2: cannot find package "os" in any of:
	/usr/lib/go/src/os (from $GOROOT)
	($GOPATH not set)
package runtime: cannot find package "runtime" in any of:
	/usr/lib/go/src/runtime (from $GOROOT)
	($GOPATH not set)
```

**Comment by andyshinn** [comment]
Go 1.4 is actually in Alpine Linux 3.2 so this package shouldn't really be needed anymore. Can you confirm if these issues can be closed? I may actually just delete this repository unless it is being used for something.

**Comment by drewwells** [comment]
It is. This is no longer needed
